### ISSUE TITLE
no configure file present

### ISSUE THREAD

**Issue by souradeep100** [OpenIKEv2/libopenikev2#5]
In the source code, no configure file, or configure.in file is present .

**Comment by alejandro-perez** [comment]
just execute `autoreconf -fi`

**Comment by souradeep100** [comment]
Hi with autoconf -fi I am getting the following error : 
souradeep@souradeep-VirtualBox ~/Sujal/libopenikev2 $ ./configure 
./configure: line 1739: syntax error near unexpected token `config.h'
./configure: line 1739: `AM_CONFIG_HEADER(config.h)'

1737 
1738 
1739 AM_CONFIG_HEADER(config.h)                                                                                                                                          
1740 

I am running autoconf -fi from libopenikev2/ .

**Comment by alejandro-perez** [comment]
Which Linux distribution are you using? Have you installed build-essential (or equivalent), meaning autoconf, automake, etc?

**Comment by souradeep100** [comment]
souradeep@souradeep-VirtualBox ~/Sujal/libopenikev2 $ uname -r
4.8.0-53-generic
souradeep@souradeep-VirtualBox ~/Sujal/libopenikev2 $ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 18.2 Sonya
Release:	18.2
Codename:	sonya

**************************************************
steps I am using : 

souradeep@souradeep-VirtualBox ~/Sujal/libopenikev2 $ autoconf -f -i
configure.ac:3: error: possibly undefined macro: AM_CONFIG_HEADER
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:6: error: possibly undefined macro: AM_INIT_AUTOMAKE
configure.ac:10: error: possibly undefined macro: AM_PROG_LIBTOOL
souradeep@souradeep-VirtualBox ~/Sujal/libopenikev2 $ ./configure
./configure: line 1739: syntax error near unexpected token `config.h'
./configure: line 1739: `AM_CONFIG_HEADER(config.h)'
souradeep@souradeep-VirtualBox ~/Sujal/libopenikev2 $ automake
configure.ac: error: no proper invocation of AM_INIT_AUTOMAKE was found.
configure.ac: You should verify that configure.ac invokes AM_INIT_AUTOMAKE,
configure.ac: that aclocal.m4 is present in the top-level directory,
configure.ac: and that aclocal.m4 was recently regenerated (using aclocal)
src/Makefile.am:4: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
src/Makefile.am:7: error: Libtool library used but 'LIBTOOL' is undefined
src/Makefile.am:7:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
src/Makefile.am:7:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
src/Makefile.am:7:   If 'LT_INIT' is in 'configure.ac', make sure
src/Makefile.am:7:   its definition is in aclocal's search path.
src/Makefile.am: error: required file './depcomp' not found
src/Makefile.am:   'automake --add-missing' can install 'depcomp'
/usr/share/automake-1.15/am/depend2.am: error: am__fastdepCXX does not appear in AM_CONDITIONAL
/usr/share/automake-1.15/am/depend2.am:   The usual way to define 'am__fastdepCXX' is to add 'AC_PROG_CXX'
/usr/share/automake-1.15/am/depend2.am:   to 'configure.ac' and run 'aclocal' and 'autoconf' again
/usr/share/automake-1.15/am/depend2.am: error: AMDEP does not appear in AM_CONDITIONAL
/usr/share/automake-1.15/am/depend2.am:   The usual way to define 'AMDEP' is to add one of the compiler tests
/usr/share/automake-1.15/am/depend2.am:     AC_PROG_CC, AC_PROG_CXX, AC_PROG_OBJC, AC_PROG_OBJCXX,
/usr/share/automake-1.15/am/depend2.am:     AM_PROG_AS, AM_PROG_GCJ, AM_PROG_UPC
/usr/share/automake-1.15/am/depend2.am:   to 'configure.ac' and run 'aclocal' and 'autoconf' again


********************
Please let me know where I am doing wrong here.

**Comment by alejandro-perez** [comment]
It seems you need to install the automake autoconf and libtool packages

Enviado con AquaMail para Android http://www.aqua-mail.com


En 3 de noviembre de 2017 19:44:31 souradeep100 <notifications@github.com> 
escribió:

**Comment by alejandro-perez** [comment]
In any case I will upload a configure file in rhe following days, as it seems like a good idea to avoid users these kind of problems. Thanks for reporting

**Comment by souradeep100** [comment]
thanks a lot for the reply and I will install libtool. Automake and autoconf was already installed. Also getting the configure file will be a great help.

**Comment by souradeep100** [comment]
Hi ,found a solution , using autoreconf --install, creates the configure file properly . Now configure script is running . Thanks .

**Comment by alejandro-perez** [comment]
Oh right!  I meant "autoreconf -fi"   my bad. I was writing from the mobile and did not realize
